// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_gwr_model_diagnostics
Rcpp::List cpp_gwr_model_diagnostics(const arma::mat& x, const arma::vec& y, const arma::vec& fitted, const arma::mat& coefficients, const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const arma::vec& x_center, const arma::vec& x_scale, const int kernel, const bool adaptive, const double fixed_bandwidth, const double lambda, const double alpha, const double d, const int penalty_mode, const double gamma, const bool return_inference, const int n_threads, const int grain_size);
RcppExport SEXP _gwrs_cpp_gwr_model_diagnostics(SEXP xSEXP, SEXP ySEXP, SEXP fittedSEXP, SEXP coefficientsSEXP, SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP x_centerSEXP, SEXP x_scaleSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP dSEXP, SEXP penalty_modeSEXP, SEXP gammaSEXP, SEXP return_inferenceSEXP, SEXP n_threadsSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fitted(fittedSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x_center(x_centerSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x_scale(x_scaleSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type d(dSEXP);
    Rcpp::traits::input_parameter< const int >::type penalty_mode(penalty_modeSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_inference(return_inferenceSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gwr_model_diagnostics(x, y, fitted, coefficients, neighbor_index, neighbor_distance, x_center, x_scale, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, penalty_mode, gamma, return_inference, n_threads, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gwr_f_test_components
Rcpp::List cpp_gwr_f_test_components(const arma::mat& x, const arma::mat& coefficients, const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const arma::vec& x_center, const arma::vec& x_scale, const int kernel, const bool adaptive, const double fixed_bandwidth, const double lambda, const double alpha, const double d, const int penalty_mode, const double gamma, const int n_threads, const int grain_size, const arma::mat& global_basis, const int block_size, const double memory_limit_mb);
RcppExport SEXP _gwrs_cpp_gwr_f_test_components(SEXP xSEXP, SEXP coefficientsSEXP, SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP x_centerSEXP, SEXP x_scaleSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP dSEXP, SEXP penalty_modeSEXP, SEXP gammaSEXP, SEXP n_threadsSEXP, SEXP grain_sizeSEXP, SEXP global_basisSEXP, SEXP block_sizeSEXP, SEXP memory_limit_mbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x_center(x_centerSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x_scale(x_scaleSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type d(dSEXP);
    Rcpp::traits::input_parameter< const int >::type penalty_mode(penalty_modeSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type grain_size(grain_sizeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type global_basis(global_basisSEXP);
    Rcpp::traits::input_parameter< const int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< const double >::type memory_limit_mb(memory_limit_mbSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gwr_f_test_components(x, coefficients, neighbor_index, neighbor_distance, x_center, x_scale, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, penalty_mode, gamma, n_threads, grain_size, global_basis, block_size, memory_limit_mb));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nonconvex_coordinate_minimum
double cpp_nonconvex_coordinate_minimum(const double score, const double curvature, const double lambda, const int penalty, const double gamma);
RcppExport SEXP _gwrs_cpp_nonconvex_coordinate_minimum(SEXP scoreSEXP, SEXP curvatureSEXP, SEXP lambdaSEXP, SEXP penaltySEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< const double >::type curvature(curvatureSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nonconvex_coordinate_minimum(score, curvature, lambda, penalty, gamma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gwr_nonconvex_lambda_max
double cpp_gwr_nonconvex_lambda_max(const arma::mat& x, const arma::vec& y, const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const int kernel, const bool adaptive, const double fixed_bandwidth, const int penalty, const double gamma, const int n_threads, const int grain_size);
RcppExport SEXP _gwrs_cpp_gwr_nonconvex_lambda_max(SEXP xSEXP, SEXP ySEXP, SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP, SEXP penaltySEXP, SEXP gammaSEXP, SEXP n_threadsSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    Rcpp::traits::input_parameter< const int >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gwr_nonconvex_lambda_max(x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, penalty, gamma, n_threads, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gwr_nonconvex_path_predict
Rcpp::List cpp_gwr_nonconvex_path_predict(const arma::mat& x_train, const arma::vec& y_train, const arma::mat& x_target, const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const int kernel, const bool adaptive, const double fixed_bandwidth, const arma::vec& lambda, const int penalty, const double gamma, const double tolerance, const int max_iterations, const bool screening, const bool keep_coefficients, const bool return_diagnostics, const int n_threads, const int grain_size, const bool guarded_block);
RcppExport SEXP _gwrs_cpp_gwr_nonconvex_path_predict(SEXP x_trainSEXP, SEXP y_trainSEXP, SEXP x_targetSEXP, SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP, SEXP lambdaSEXP, SEXP penaltySEXP, SEXP gammaSEXP, SEXP toleranceSEXP, SEXP max_iterationsSEXP, SEXP screeningSEXP, SEXP keep_coefficientsSEXP, SEXP return_diagnosticsSEXP, SEXP n_threadsSEXP, SEXP grain_sizeSEXP, SEXP guarded_blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x_train(x_trainSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_train(y_trainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x_target(x_targetSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< const bool >::type screening(screeningSEXP);
    Rcpp::traits::input_parameter< const bool >::type keep_coefficients(keep_coefficientsSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_diagnostics(return_diagnosticsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type grain_size(grain_sizeSEXP);
    Rcpp::traits::input_parameter< const bool >::type guarded_block(guarded_blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gwr_nonconvex_path_predict(x_train, y_train, x_target, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, penalty, gamma, tolerance, max_iterations, screening, keep_coefficients, return_diagnostics, n_threads, grain_size, guarded_block));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gwr_sl_grid_predict
Rcpp::List cpp_gwr_sl_grid_predict(const arma::mat& x_train, const arma::vec& y_train, const arma::mat& x_target, const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const int kernel, const bool adaptive, const double fixed_bandwidth, const arma::vec& lambda, const arma::vec& alpha, const arma::vec& d, const double tolerance, const int max_iterations, const bool screening, const bool keep_coefficients, const bool active_solve);
RcppExport SEXP _gwrs_cpp_gwr_sl_grid_predict(SEXP x_trainSEXP, SEXP y_trainSEXP, SEXP x_targetSEXP, SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP dSEXP, SEXP toleranceSEXP, SEXP max_iterationsSEXP, SEXP screeningSEXP, SEXP keep_coefficientsSEXP, SEXP active_solveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x_train(x_trainSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_train(y_trainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x_target(x_targetSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< const bool >::type screening(screeningSEXP);
    Rcpp::traits::input_parameter< const bool >::type keep_coefficients(keep_coefficientsSEXP);
    Rcpp::traits::input_parameter< const bool >::type active_solve(active_solveSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gwr_sl_grid_predict(x_train, y_train, x_target, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, tolerance, max_iterations, screening, keep_coefficients, active_solve));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gwr_sl_lambda_max
double cpp_gwr_sl_lambda_max(const arma::mat& x, const arma::vec& y, const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const int kernel, const bool adaptive, const double fixed_bandwidth, const double alpha, const int n_threads, const int grain_size);
RcppExport SEXP _gwrs_cpp_gwr_sl_lambda_max(SEXP xSEXP, SEXP ySEXP, SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP, SEXP alphaSEXP, SEXP n_threadsSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gwr_sl_lambda_max(x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, alpha, n_threads, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gwr_sl_path_predict
Rcpp::List cpp_gwr_sl_path_predict(const arma::mat& x_train, const arma::vec& y_train, const arma::mat& x_target, const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const int kernel, const bool adaptive, const double fixed_bandwidth, const arma::vec& lambda, const double alpha, const double d, const double tolerance, const int max_iterations, const bool screening, const bool keep_coefficients, const bool return_diagnostics, const int n_threads, const int grain_size);
RcppExport SEXP _gwrs_cpp_gwr_sl_path_predict(SEXP x_trainSEXP, SEXP y_trainSEXP, SEXP x_targetSEXP, SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP dSEXP, SEXP toleranceSEXP, SEXP max_iterationsSEXP, SEXP screeningSEXP, SEXP keep_coefficientsSEXP, SEXP return_diagnosticsSEXP, SEXP n_threadsSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x_train(x_trainSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_train(y_trainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x_target(x_targetSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type d(dSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< const bool >::type screening(screeningSEXP);
    Rcpp::traits::input_parameter< const bool >::type keep_coefficients(keep_coefficientsSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_diagnostics(return_diagnosticsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gwr_sl_path_predict(x_train, y_train, x_target, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, tolerance, max_iterations, screening, keep_coefficients, return_diagnostics, n_threads, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gwr_sl_fit
Rcpp::List cpp_gwr_sl_fit(const arma::mat& x, const arma::vec& y, const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const int kernel, const bool adaptive, const double fixed_bandwidth, const double lambda, const double alpha, const double d, const double tolerance, const int max_iterations, const int n_threads, const int grain_size);
RcppExport SEXP _gwrs_cpp_gwr_sl_fit(SEXP xSEXP, SEXP ySEXP, SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP dSEXP, SEXP toleranceSEXP, SEXP max_iterationsSEXP, SEXP n_threadsSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type d(dSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gwr_sl_fit(x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, tolerance, max_iterations, n_threads, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_arma_uword_bits
int cpp_arma_uword_bits();
RcppExport SEXP _gwrs_cpp_arma_uword_bits() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_arma_uword_bits());
    return rcpp_result_gen;
END_RCPP
}
// cpp_graph_laplacian
arma::sp_mat cpp_graph_laplacian(const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const int kernel, const bool adaptive, const double fixed_bandwidth);
RcppExport SEXP _gwrs_cpp_graph_laplacian(SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_graph_laplacian(neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gwr_ktdd_fit
Rcpp::List cpp_gwr_ktdd_fit(const arma::mat& x, const arma::vec& y, const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const int kernel, const bool adaptive, const double fixed_bandwidth, const arma::sp_mat& diffusion_operator, const arma::vec& source, const arma::sp_mat& coefficient_laplacian, const double lambda_diffusion, const double gamma, const int coefficient_solver, const double coefficient_tolerance, const int coefficient_max_iterations, const double tolerance, const int max_iterations, const double linear_tolerance, const int linear_max_iterations, const bool center_process, const int n_threads, const int grain_size);
RcppExport SEXP _gwrs_cpp_gwr_ktdd_fit(SEXP xSEXP, SEXP ySEXP, SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP, SEXP diffusion_operatorSEXP, SEXP sourceSEXP, SEXP coefficient_laplacianSEXP, SEXP lambda_diffusionSEXP, SEXP gammaSEXP, SEXP coefficient_solverSEXP, SEXP coefficient_toleranceSEXP, SEXP coefficient_max_iterationsSEXP, SEXP toleranceSEXP, SEXP max_iterationsSEXP, SEXP linear_toleranceSEXP, SEXP linear_max_iterationsSEXP, SEXP center_processSEXP, SEXP n_threadsSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type diffusion_operator(diffusion_operatorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type source(sourceSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type coefficient_laplacian(coefficient_laplacianSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_diffusion(lambda_diffusionSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const int >::type coefficient_solver(coefficient_solverSEXP);
    Rcpp::traits::input_parameter< const double >::type coefficient_tolerance(coefficient_toleranceSEXP);
    Rcpp::traits::input_parameter< const int >::type coefficient_max_iterations(coefficient_max_iterationsSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< const double >::type linear_tolerance(linear_toleranceSEXP);
    Rcpp::traits::input_parameter< const int >::type linear_max_iterations(linear_max_iterationsSEXP);
    Rcpp::traits::input_parameter< const bool >::type center_process(center_processSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gwr_ktdd_fit(x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, diffusion_operator, source, coefficient_laplacian, lambda_diffusion, gamma, coefficient_solver, coefficient_tolerance, coefficient_max_iterations, tolerance, max_iterations, linear_tolerance, linear_max_iterations, center_process, n_threads, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lad_gwr_sl_fit
Rcpp::List cpp_lad_gwr_sl_fit(const arma::mat& x, const arma::vec& y, const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const int kernel, const bool adaptive, const double fixed_bandwidth, const double lambda, const double alpha, const double d, const double rho_residual, const double rho_penalty, const double tolerance, const int max_iterations, const int n_threads, const int grain_size);
RcppExport SEXP _gwrs_cpp_lad_gwr_sl_fit(SEXP xSEXP, SEXP ySEXP, SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP dSEXP, SEXP rho_residualSEXP, SEXP rho_penaltySEXP, SEXP toleranceSEXP, SEXP max_iterationsSEXP, SEXP n_threadsSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type d(dSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_residual(rho_residualSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_penalty(rho_penaltySEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lad_gwr_sl_fit(x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, rho_residual, rho_penalty, tolerance, max_iterations, n_threads, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gwr_global_collinearity
Rcpp::List cpp_gwr_global_collinearity(const arma::mat& x);
RcppExport SEXP _gwrs_cpp_gwr_global_collinearity(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gwr_global_collinearity(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gwr_local_collinearity
Rcpp::List cpp_gwr_local_collinearity(const arma::mat& x, const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const int kernel, const bool adaptive, const double fixed_bandwidth, const bool center, const bool scale, const bool return_pairwise, const int n_threads, const int grain_size);
RcppExport SEXP _gwrs_cpp_gwr_local_collinearity(SEXP xSEXP, SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP, SEXP centerSEXP, SEXP scaleSEXP, SEXP return_pairwiseSEXP, SEXP n_threadsSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    Rcpp::traits::input_parameter< const bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< const bool >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_pairwise(return_pairwiseSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gwr_local_collinearity(x, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, center, scale, return_pairwise, n_threads, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gwr_local_residual_diagnostics
Rcpp::List cpp_gwr_local_residual_diagnostics(const arma::vec& y, const arma::vec& fitted, const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const int kernel, const bool adaptive, const double fixed_bandwidth, const int n_threads, const int grain_size);
RcppExport SEXP _gwrs_cpp_gwr_local_residual_diagnostics(SEXP ySEXP, SEXP fittedSEXP, SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP, SEXP n_threadsSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fitted(fittedSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gwr_local_residual_diagnostics(y, fitted, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, n_threads, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gwr_moran
Rcpp::List cpp_gwr_moran(const arma::vec& residuals, const arma::umat& neighbor_index, const arma::mat& neighbor_distance, const int kernel, const bool adaptive, const double fixed_bandwidth, const bool row_standardize, const int permutations, const double seed, const int n_threads, const int grain_size);
RcppExport SEXP _gwrs_cpp_gwr_moran(SEXP residualsSEXP, SEXP neighbor_indexSEXP, SEXP neighbor_distanceSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP fixed_bandwidthSEXP, SEXP row_standardizeSEXP, SEXP permutationsSEXP, SEXP seedSEXP, SEXP n_threadsSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type neighbor_index(neighbor_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type neighbor_distance(neighbor_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type fixed_bandwidth(fixed_bandwidthSEXP);
    Rcpp::traits::input_parameter< const bool >::type row_standardize(row_standardizeSEXP);
    Rcpp::traits::input_parameter< const int >::type permutations(permutationsSEXP);
    Rcpp::traits::input_parameter< const double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gwr_moran(residuals, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, row_standardize, permutations, seed, n_threads, grain_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gwrs_cpp_gwr_model_diagnostics", (DL_FUNC) &_gwrs_cpp_gwr_model_diagnostics, 19},
    {"_gwrs_cpp_gwr_f_test_components", (DL_FUNC) &_gwrs_cpp_gwr_f_test_components, 19},
    {"_gwrs_cpp_nonconvex_coordinate_minimum", (DL_FUNC) &_gwrs_cpp_nonconvex_coordinate_minimum, 5},
    {"_gwrs_cpp_gwr_nonconvex_lambda_max", (DL_FUNC) &_gwrs_cpp_gwr_nonconvex_lambda_max, 11},
    {"_gwrs_cpp_gwr_nonconvex_path_predict", (DL_FUNC) &_gwrs_cpp_gwr_nonconvex_path_predict, 19},
    {"_gwrs_cpp_gwr_sl_grid_predict", (DL_FUNC) &_gwrs_cpp_gwr_sl_grid_predict, 16},
    {"_gwrs_cpp_gwr_sl_lambda_max", (DL_FUNC) &_gwrs_cpp_gwr_sl_lambda_max, 10},
    {"_gwrs_cpp_gwr_sl_path_predict", (DL_FUNC) &_gwrs_cpp_gwr_sl_path_predict, 18},
    {"_gwrs_cpp_gwr_sl_fit", (DL_FUNC) &_gwrs_cpp_gwr_sl_fit, 14},
    {"_gwrs_cpp_arma_uword_bits", (DL_FUNC) &_gwrs_cpp_arma_uword_bits, 0},
    {"_gwrs_cpp_graph_laplacian", (DL_FUNC) &_gwrs_cpp_graph_laplacian, 5},
    {"_gwrs_cpp_gwr_ktdd_fit", (DL_FUNC) &_gwrs_cpp_gwr_ktdd_fit, 22},
    {"_gwrs_cpp_lad_gwr_sl_fit", (DL_FUNC) &_gwrs_cpp_lad_gwr_sl_fit, 16},
    {"_gwrs_cpp_gwr_global_collinearity", (DL_FUNC) &_gwrs_cpp_gwr_global_collinearity, 1},
    {"_gwrs_cpp_gwr_local_collinearity", (DL_FUNC) &_gwrs_cpp_gwr_local_collinearity, 11},
    {"_gwrs_cpp_gwr_local_residual_diagnostics", (DL_FUNC) &_gwrs_cpp_gwr_local_residual_diagnostics, 9},
    {"_gwrs_cpp_gwr_moran", (DL_FUNC) &_gwrs_cpp_gwr_moran, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_gwrs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
