# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_gwr_model_diagnostics <- function(x, y, fitted, coefficients, neighbor_index, neighbor_distance, x_center, x_scale, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, penalty_mode, gamma, return_inference, n_threads, grain_size) {
    .Call(`_gwrs_cpp_gwr_model_diagnostics`, x, y, fitted, coefficients, neighbor_index, neighbor_distance, x_center, x_scale, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, penalty_mode, gamma, return_inference, n_threads, grain_size)
}

cpp_gwr_f_test_components <- function(x, coefficients, neighbor_index, neighbor_distance, x_center, x_scale, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, penalty_mode, gamma, n_threads, grain_size, global_basis, block_size, memory_limit_mb) {
    .Call(`_gwrs_cpp_gwr_f_test_components`, x, coefficients, neighbor_index, neighbor_distance, x_center, x_scale, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, penalty_mode, gamma, n_threads, grain_size, global_basis, block_size, memory_limit_mb)
}

cpp_nonconvex_coordinate_minimum <- function(score, curvature, lambda, penalty, gamma) {
    .Call(`_gwrs_cpp_nonconvex_coordinate_minimum`, score, curvature, lambda, penalty, gamma)
}

cpp_gwr_nonconvex_lambda_max <- function(x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, penalty, gamma, n_threads, grain_size) {
    .Call(`_gwrs_cpp_gwr_nonconvex_lambda_max`, x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, penalty, gamma, n_threads, grain_size)
}

cpp_gwr_nonconvex_path_predict <- function(x_train, y_train, x_target, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, penalty, gamma, tolerance, max_iterations, screening, keep_coefficients, return_diagnostics, n_threads, grain_size, guarded_block = FALSE) {
    .Call(`_gwrs_cpp_gwr_nonconvex_path_predict`, x_train, y_train, x_target, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, penalty, gamma, tolerance, max_iterations, screening, keep_coefficients, return_diagnostics, n_threads, grain_size, guarded_block)
}

cpp_gwr_sl_grid_predict <- function(x_train, y_train, x_target, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, tolerance, max_iterations, screening, keep_coefficients, active_solve = FALSE) {
    .Call(`_gwrs_cpp_gwr_sl_grid_predict`, x_train, y_train, x_target, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, tolerance, max_iterations, screening, keep_coefficients, active_solve)
}

cpp_gwr_sl_lambda_max <- function(x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, alpha, n_threads, grain_size) {
    .Call(`_gwrs_cpp_gwr_sl_lambda_max`, x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, alpha, n_threads, grain_size)
}

cpp_gwr_sl_path_predict <- function(x_train, y_train, x_target, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, tolerance, max_iterations, screening, keep_coefficients, return_diagnostics, n_threads, grain_size) {
    .Call(`_gwrs_cpp_gwr_sl_path_predict`, x_train, y_train, x_target, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, tolerance, max_iterations, screening, keep_coefficients, return_diagnostics, n_threads, grain_size)
}

cpp_gwr_sl_fit <- function(x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, tolerance, max_iterations, n_threads, grain_size) {
    .Call(`_gwrs_cpp_gwr_sl_fit`, x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, tolerance, max_iterations, n_threads, grain_size)
}

cpp_arma_uword_bits <- function() {
    .Call(`_gwrs_cpp_arma_uword_bits`)
}

cpp_graph_laplacian <- function(neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth) {
    .Call(`_gwrs_cpp_graph_laplacian`, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth)
}

cpp_gwr_ktdd_fit <- function(x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, diffusion_operator, source, coefficient_laplacian, lambda_diffusion, gamma, coefficient_solver, coefficient_tolerance, coefficient_max_iterations, tolerance, max_iterations, linear_tolerance, linear_max_iterations, center_process, n_threads, grain_size) {
    .Call(`_gwrs_cpp_gwr_ktdd_fit`, x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, diffusion_operator, source, coefficient_laplacian, lambda_diffusion, gamma, coefficient_solver, coefficient_tolerance, coefficient_max_iterations, tolerance, max_iterations, linear_tolerance, linear_max_iterations, center_process, n_threads, grain_size)
}

cpp_lad_gwr_sl_fit <- function(x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, rho_residual, rho_penalty, tolerance, max_iterations, n_threads, grain_size) {
    .Call(`_gwrs_cpp_lad_gwr_sl_fit`, x, y, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, lambda, alpha, d, rho_residual, rho_penalty, tolerance, max_iterations, n_threads, grain_size)
}

cpp_gwr_global_collinearity <- function(x) {
    .Call(`_gwrs_cpp_gwr_global_collinearity`, x)
}

cpp_gwr_local_collinearity <- function(x, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, center, scale, return_pairwise, n_threads, grain_size) {
    .Call(`_gwrs_cpp_gwr_local_collinearity`, x, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, center, scale, return_pairwise, n_threads, grain_size)
}

cpp_gwr_local_residual_diagnostics <- function(y, fitted, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, n_threads, grain_size) {
    .Call(`_gwrs_cpp_gwr_local_residual_diagnostics`, y, fitted, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, n_threads, grain_size)
}

cpp_gwr_moran <- function(residuals, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, row_standardize, permutations, seed, n_threads, grain_size) {
    .Call(`_gwrs_cpp_gwr_moran`, residuals, neighbor_index, neighbor_distance, kernel, adaptive, fixed_bandwidth, row_standardize, permutations, seed, n_threads, grain_size)
}

